apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-custom-default-branch-uvbj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-custom-default-branch-uvbj
    app.kubernetes.io/part-of: build-suite-test-application-kczy
  name: test-custom-default-branch-uvbj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-custom-default-branch-uvbj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-custom-default-branch-uvbj
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-rorf-tenant/build-suite-test-application-kczy/test-custom-default-branch-uvbj@sha256:bc472fba32b626809f02c45e6e9b0268ba1cc399c0f8451236016f9645030e0b
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
